### ISSUE TITLE
Unable to use DeriveActiveEnum due to cannot find trait TryGetableArray and ActiveEnumValue

### ISSUE THREAD

**Issue by zhengcan** [SeaQL/sea-orm#1930]
## Description

`DeriveActiveEnum` doesn't work in 0.12.4. 

## Steps to Reproduce

1. I've declared an enum by deriving DeriveActiveEnum as below

```
#[derive(Clone, Copy, Debug, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "u32", db_type = "Unsigned")]
pub enum MyEnum {
    #[sea_orm(num_value = 0)]
    First,
    #[sea_orm(num_value = 1)]
    Second,
}
```

2. The rustc reports several errors

```
error[E0405]: cannot find trait `TryGetableArray` in crate `sea_orm`
...
6   | #[derive(Clone, Copy, Debug, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
    |                                                   ^^^^^^^^^^^^^^^^ help: a trait with a similar name exists: `TryGetableMany`
    |
   ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.2/src/executor/query.rs:812:1
    |
812 | pub trait TryGetableMany: Sized {
    | ------------------------------- similarly named trait `TryGetableMany` defined here
    |
    = note: this error originates in the derive macro `DeriveActiveEnum` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `ActiveEnumValue` in crate `sea_orm`
...
6   | #[derive(Clone, Copy, Debug, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
    |                                                   ^^^^^^^^^^^^^^^^ help: a trait with a similar name exists: `ActiveEnum`
    |
   ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-0.12.2/src/entity/active_enum.rs:112:1
    |
112 | pub trait ActiveEnum: Sized + Iterable {
    | -------------------------------------- similarly named trait `ActiveEnum` defined here
    |
    = note: this error originates in the derive macro `DeriveActiveEnum` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Expected Behavior

My code compiled successfully.

### Actual Behavior

Compile failed.

### Reproduces How Often

Always in 0.12.4

### Workarounds

Rollback to old version

## Reproducible Example

n/a

## Versions

0.12.3

## Comment

The `TryGetableArray` and `ActiveEnumValue` are introduced in 3 weeks ago, and they are not visible under root mod of `sea_orm`.
Please export them as public trait.

**Comment by tyt2y3** [comment]
Thank you for your report, let me make a patch.

**Comment by tyt2y3** [comment]
I just bumped sea-orm-macros https://crates.io/crates/sea-orm-macros/versions
Can you check if it works for you?

**Comment by zhengcan** [comment]
> I just bumped sea-orm-macros https://crates.io/crates/sea-orm-macros/versions Can you check if it works for you?

It works!

**Comment by tyt2y3** [comment]
Thank you!
