### ISSUE TITLE
Before_save hooks doesn't work on 1.1.13

### ISSUE THREAD

**Issue by Shawn25** [SeaQL/sea-orm#2646]
before_save fuction like in doc （https://www.sea-ql.org/SeaORM/docs/next/generate-entity/entity-structure/）: 

```
async fn before_save<C>(self, db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if self.price.as_ref() <= &0.0 {
            Err(DbErr::Custom(format!(
                "[before_save] Invalid Price, insert: {}",
                insert
            )))
        } else {
            Ok(self)
        }
    }
```

this could not compile, got err:

error[E0195]: lifetime parameters or bounds on method `before_save` do not match the trait declaration

**Comment by Huliiiiii** [comment]
Did you use `#[async_trait]`?
