### ISSUE TITLE
use of unstable library feature 'error_in_core'

### ISSUE THREAD

**Issue by sunliang711** [SeaQL/sea-orm#2429]
## Steps to Reproduce

1. git clone https://github.com/SeaQL/sea-orm
2. cd sea-orm/examples/basic
3. cargo run

### Expected Behavior

program should be compiled successfully and run

### Actual Behavior

compile with error: error[E0658]: use of unstable library feature 'error_in_core'
<img width="806" alt="image" src="https://github.com/user-attachments/assets/070aed5b-1b14-40f8-b975-a5a3bcf47198">

even when I create a hello world project ,and add sea-orm to cargo.toml, the project also report this error.
My rust version info:
cargo 1.78.0 (54d8815d0 2024-03-26)
rustc 1.78.0 (9b00956e5 2024-04-29)

**Comment by tyt2y3** [comment]
oh, it's the MSRV of the idna crate, which I don't maintain. you can try updating your rustc to at least 1.80

**Comment by conradogarciaberrotaran** [comment]
I had 1.80.0 and the error still persisted:
```bash
$ rustc --version
rustc 1.80.0 (051478957 2024-07-21)
```

After updating to 1.83 using `rustup update`, the issue was fixed.

```$ rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
```

I would close the issue.

**Comment by tyt2y3** [comment]
I can confirm that the MSRV is 1.81

**Comment by Fenex** [comment]
Sad news.

`sea-orm 1.1.1` - is the last version that can be compiled by rustc 1.75.
`rustc 1.75` - is the last version with prebuilt toolchain binaries that can be running on Windows 7.

I post this comment to help others find out last version of sqlx to compile under Windows 7.
