### ISSUE TITLE
sea-orm "2.0.0-rc.3" does not build on mac os, rust 1.89

### ISSUE THREAD

**Issue by NikMamco** [SeaQL/sea-orm#2696]
## Description
My project does not build 
this is my Cargo.toml:  
```toml
sea-orm = { version = "2.0.0-rc.3", features = ["sqlx-mysql", "sqlx-sqlite", "runtime-tokio-rustls", "macros", "debug-print"] }

sea-orm-migration = { version = "2.0.0-rc.3", features = ["runtime-tokio-rustls", "sqlx-mysql", "sqlx-sqlite"] }
```
with a cargo build I get those errors: 

```
error[E0106]: missing lifetime specifier
 --> /Users/francescomei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sea-schema-0.17.0-rc.5/src/parser.rs:6:17
  |
6 |     pub tokens: Tokenizer,
  |                 ^^^^^^^^^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
5 ~ pub struct Parser<'a> {
6 ~     pub tokens: Tokenizer<'a>,
  |

error[E0106]: missing lifetime specifier
 --> /Users/francescomei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sea-schema-0.17.0-rc.5/src/parser.rs:7:22
  |
7 |     pub curr: Option<Token>,
  |                      ^^^^^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
5 ~ pub struct Parser<'a> {
6 |     pub tokens: Tokenizer,
7 ~     pub curr: Option<Token<'a>>,
  |

error[E0106]: missing lifetime specifier
 --> /Users/francescomei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sea-schema-0.17.0-rc.5/src/parser.rs:8:22
  |
8 |     pub last: Option<Token>,
  |                      ^^^^^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
5 ~ pub struct Parser<'a> {
6 |     pub tokens: Tokenizer,
7 |     pub curr: Option<Token>,
8 ~     pub last: Option<Token<'a>>,
  |

error[E0432]: unresolved import `sea_query::inject_parameters`
 --> /Users/francescomei/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sea-orm-2.0.0-rc.3/src/database/statement.rs:4:78
  |
4 | use sea_query::{MysqlQueryBuilder, PostgresQueryBuilder, SqliteQueryBuilder, inject_parameters};
  |                                                                              ^^^^^^^^^^^^^^^^^ no `inject_parameters` in the root
```

## Steps to Reproduce

1. On a mac os system create a new project with the dependencies on sea-orm and sea-orm-migration
2. Run cargo build

### Expected Behavior
the project compiles successfully 

### Actual Behavior
Errors in description occurs

### Reproduces How Often

 always

**Comment by Huliiiiii** [comment]
This is related to the latest changes of sea query. You can try to pin the version of sea query.

**Comment by NikMamco** [comment]
Ok thanks, for now I'll pin to version 1.14.

**Comment by Huliiiiii** [comment]
This issue should be fixed now.
